### ISSUE TITLE
Bad entries in metadata file

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/bc-incubation2018#1]
@AditiGit what am I supposed to do with these entries in the `BeaverCreek_2018Incubation_PICARRO_Metadata.xlsx` file?

<img width="476" alt="Screen Shot 2019-06-04 at 1 21 54 AM" src="https://user-images.githubusercontent.com/1956468/58853136-29a5dc80-8667-11e9-842e-47558bf76d7c.png">

Please do NOT unilaterally fix them, rather tell me. Thanks.

**Comment by AditiGit** [comment]
yikes . Okay, entries 1788-1799 ran from 2.10-3.12 pm. Entries 1800-1811 ran from 3.26-4.28 pm.

**Comment by bpbond** [comment]
OK, thanks. Fixed.
