### ISSUE TITLE
Core column in metadata file

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/bc-incubation2018#2]
In `BeaverCreek_2018Incubation_PICARRO_Metadata.xlsx` the Core column has values like  BC3-5, BC3-3, BC3-2, BC4-12, BC2-13...

But over in `Copy of Aditi's Data.xlsx` the ID values look like BC-2-1-Pre, BC-2-2-Pre, BC-3-1-Pre, BC-3-2-Pre

How do they related to each other? What do they mean?

**Comment by AditiGit** [comment]
Please use BeaverCreek_2018Incubation_PICARRO_Metadata.xlsx. Do not use the Copy of Aditi's Data file. Five cores from each site were sacrificed pre-inundation, the Pre-signifies this. But ignore for your purpose. I was planning to add a complete metadata file (with treatment conditions, soil chemistry data, soil moisture) later. If you want this information now, let me know and I can modify the Metadata file accordingly. haven't received the chemistry data yet but the least I can do is add the pre/post/control information.

**Comment by bpbond** [comment]
Okay.
